name: Jira

on:
  pull_request:
    types:
      - opened
    branches:
      - main

jobs:
  create_jira:
    name: Dependabot Jira
    runs-on: ubuntu-latest
    #if: github.event.pull_request.user.id == 27856297
    steps:
    - name: Validate
      run: |
        echo "The GitHub Action Secret will be masked:  "
        echo ${{ secrets.JIRA_BASE_URL }}
      
    - name: Login to Jira
      uses: atlassian/gajira-login@v2.0.0
      env:
        JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
        JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

    - name: Create Jira Issue
      id: create
      uses: atlassian/gajira-create@v2.0.1
      with:
        project: ${{ secrets.JIRA_PROJECT }}
        issuetype: ${{ secrets.JIRA_ISSUE_TYPE }}
        summary: |
          [${{github.event.repository.name }}] ${{github.event.pull_request.title }}
        description: |
          ${{github.event.pull_request.html_url }}
